name: Feature Test

on:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  unit_tests:
    name: 'Run Apex tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz | tar xJ -C sfdx --strip-components 1
          echo $(realpath sfdx/bin) >> $GITHUB_PATH
      - name: Authenticate Dev Hub
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d
      - name: Create Scratch Org
        run:  
          sfdx force:org:create --setdefaultusername --setalias dev1 -f config/project-scratch-def.json
      - name: Deploy Code
        run:
          sfdx force:source:push
      - name: Delete Scratch org
        run:
          sfdx force:org:delete 
